language: node_js
node_js: "lts/*"
services:
  - xvfb
before_install:
  - 'npm install -g typescript'
install:
  - 'npm install'
  - 'npm install -g vsce'
  - 'vsce package'
deploy:	
  - provider: script	
    script: vsce publish -p $VSCODE_TOKEN	
    skip_cleanup: true	
    on:	
      repo: designer-for-camel/camel-designer	
      branch: master	
      tags: true
cache:
  directories:
    - "node_modules"
env: DISPLAY=:99
branches:
  except:
    - /^dependabot.*$/
